version: '3.9'
services:
  backend:
    build:
      context: .
      args:
        - JAR_FILE=./app/build/libs/app.jar
    container_name: backend
    depends_on:
      - mongodb
    ports:
      - "8081:8081"
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
networks:
  wishlist:
    external: true