spring:
  data:
    mongodb:
      uri: mongodb://${DATA_BASE_HOST:localhost}:27017
      database: wishlist
  application:
    name: wishlist
server:
  port: '8081'
springdoc:
  swagger-ui:
    path: /api-docs/index.html
logging:
  pattern:
    level: "%5p [${spring.application.name:} %X{traceId:-}] "