spring:
  application:
    name: wishlist
server:
  port: '8081'
springdoc:
  swagger-ui:
    path: /api-docs/index.html
logging:
  pattern:
    level: "%5p [${spring.application.name:} %X{traceId:-}] "